// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fpkuzqamfgorxyffhyrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwa3V6cWFtZmdvcnh5ZmZoeXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzM4OTQsImV4cCI6MjA2MjEwOTg5NH0.YLjOSU_cvN-ngRyuZJTxHVs5Qne7-n_EzYy7W7K6ezw";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);